---
- name: Verificar Consumo de Mem      ria em MB no Windows
  hosts: all
  gather_facts: yes
  tasks:
    - name: Obter informa            es sobre o consumo de mem      ria
      win_shell: Get-CimInstance -ClassName Win32_OperatingSystem | Select-Obje>
      register: memoria_info

    - name: Exibir informa            es
      debug:
        var: memoria_info.stdout_lines
