---
- hosts: "{{onda_name}}"
  gather_facts: no

  tasks:
    - name: Cria Pasta WindowsUpdate
      win_regedit:
        path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate'

    - name: Cria Pasta AU
      win_regedit:
        path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU'

    - name: Configuração Registro Windows - 192.168.254.189
      win_regedit:
        path: "{{ item.path }}"
        name: "{{ item.name }}"
        data: "{{ item.data }}"
        type: "{{ item.type }}"
      with_items:
          - {
              path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate',
              name: WUServer,
              data: 'http://192.168.254.189',
              type: string
            }
          - {
              path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate',
              name: WUStatusServer,
              data: 'http://192.168.254.189',
              type: string
            }
          - {
              path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU',
              name: AUOptions,
              data: "3",
              type: dword
              }
          - {
              path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU',
              name: DetectionFrequency,
              data: "22",
              type: dword
              }
          - {
              path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU',
              name: DetectionFrequencyEnabled,
              data: "1",
              type: dword
            }
          - {
              path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU',
              name: NoAutoRebootWithLoggedOnUsers,
              data: "1",
              type: dword
            }
          - {
              path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU',
              name: NoAutoUpdate,
              data: "0",
              type: dword
            }
          - {
              path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU',
              name: ScheduledInstallDay,
              data: "0",
              type: dword
            }
          - {
              path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU',
              name: ScheduledInstallTime,
              data: "3",
              type: dword
            }
          - {
              path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU',
              name: UseWUServer,
              data: "1",
              type: dword
            }

    - name: Forcar Replicacao
      win_shell: |
        $i=0
        while($i -le 3){
            wuauclt /detectnow
            (New-Object -ComObject Microsoft.Update.AutoUpdate).DetectNow()
            wuauclt /reportnow
            $i++
        }
