---
- hosts: windows
  gather_facts: no
  tasks:
    - name: Forcar Replicacao
      win_shell: |
        $i=0
        while($i -le 3){
            wuauclt /detectnow
            (New-Object -ComObject Microsoft.Update.AutoUpdate).DetectNow()
            wuauclt /reportnow
            $i++
        }
